name: runs on camb
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

env:
  DEEPLINK_PATH: '/mnt/cache/share/deeplinkci/github/${{ github.repository }}'

concurrency:
  group: camb-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  checkout_code:
    name: checkout code
    runs-on: tps-camb-ci
    steps:
      - name: Checkout Code
        uses: DeepLink-org/ditorch/.github/actions/checkout-code@main

  Build:
    name: build on camb
    runs-on: tps-camb-ci
    needs: [checkout_code]
    steps:
      - name: build
        run: |
          set -ex
          cd ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER} && rm -rf ${GITHUB_JOB} && cp -R source ${GITHUB_JOB}  && cd ${GITHUB_JOB}
          echo "start to build"

  Test:
    name: test on camb
    runs-on: tps-camb-ci
    needs: [Build]
    steps:
      - name: test
        run: |
          set -ex
          cd ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER} && rm -rf ${GITHUB_JOB} && cp -R Build ${GITHUB_JOB}  && cd ${GITHUB_JOB}
          echo "start to test"
          # bash ci/test.sh